"""
Configuration for YOLO training on mixed ROADWork + BDD dataset.
This dictionary follows the parameters expected by ultralytics.YOLO.train().
"""

yolo_config = {
    # -------------------- Model and data --------------------
    'model_name': 'yolov8m.pt',          # Pre-trained weights: medium version
    'data': 'data/yolo/data.yaml',       # Dataset config file (generated by prepare script)
    'device': 'cuda',                     # Use GPU

    # -------------------- Training hyperparameters --------------------
    'batch': 16,                           # Batch size per GPU (adjust based on GPU memory)
    # 'batch': 64,
    'imgsz': 640,                          # Input image size (standard for YOLOv8)
    'workers': 12,                           # Number of dataloader workers

    # Stage 1: Freeze backbone
    'stage1_epochs': 15,                    # Number of epochs for frozen stage
    'freeze': 10,                            # Freeze first 10 layers (backbone)
    'lr0_stage1': 0.001,                     # Initial learning rate (typical for fine-tuning)
    # 'lr0_stage1': 0.004, 
    'stage1_name': 'yolo/stage1',                  # Experiment subfolder name

    # Stage 2: Full fine-tuning
    'stage2_epochs': 30,                     # Additional epochs for full fine-tuning
    'lr0_stage2': 0.0001,                     # Lower learning rate for fine-tuning
    # 'lr0_stage2': 0.0004,
    'stage2_name': 'yolo/stage2',                  # Experiment subfolder name

    # Common optimizer settings
    'optimizer': 'SGD',                       # Optimizer type (SGD with momentum is robust)
    'momentum': 0.937,                         # SGD momentum (YOLOv8 default)
    'weight_decay': 0.0005,                    # Weight decay (YOLOv8 default)

    # Learning rate schedule
    'lrf': 0.01,                               # Final LR factor (LR = lr0 * lrf at end)
    'warmup_epochs': 3.0,                      # Warmup epochs (YOLOv8 default)
    'warmup_momentum': 0.8,                    # Warmup initial momentum
    'warmup_bias_lr': 0.1,                     # Warmup initial bias LR

    # Data augmentation (YOLOv8 defaults, suitable for detection)
    'hsv_h': 0.015,                            # HSV-Hue augmentation
    'hsv_s': 0.7,                               # HSV-Saturation augmentation
    'hsv_v': 0.4,                               # HSV-Value augmentation
    'degrees': 0.0,                             # Rotation (0 = no rotation, as road scenes are upright)
    'translate': 0.1,                           # Translation
    'scale': 0.5,                               # Scaling
    'shear': 0.0,                               # Shear (usually not needed)
    'perspective': 0.0,                         # Perspective (not needed)
    'flipud': 0.0,                              # Vertical flip (not common in driving)
    'fliplr': 0.5,                              # Horizontal flip (common, probability 0.5)
    'mosaic': 1.0,                              # Mosaic augmentation (YOLOv8 default, on)
    'mixup': 0.0,                                # Mixup (disabled initially, can be enabled later)

    # -------------------- Experiment tracking --------------------
    'project': None,                     # Root directory for logs and checkpoints
    'seed': 42,                                  # Random seed for reproducibility
}